var createPostPresenter = new CreatePostPresenter()
var profilePresenter = new ProfilePresenter()
var loginPresenter = new LoginPresenter()
var statusPresenter = new StatusPresenter()
var storyPresenter = new StoryPresenter()
var feedPresenter = new FeedPresenter()
var userPresenter = new UserPresenter()
var mentionsPresenter = new MentionsPresenter()